// 钓鱼事件脚本（薄壳）：通用逻辑见 lib/wt_fishing.js
var rsc = server.getPluginManager().getPlugin('RykenSlimefunCustomizer').getDataFolder();
var base = new java.io.File(rsc, 'addons/WorldTaste/scripts');
var code = new java.lang.String(Files.readAllBytes(Paths.get(base.getPath(), 'lib/wt_fishing.js')), 'UTF-8');
(0, eval)(code);

const DANSHUIYUER_DROPS = [
    { itemId: "LILY_PAD", weight: 10 },
    { itemId: "TADPOLE_BUCKET", weight: 20 },
    { itemId: "AXOLOTL_BUCKET", weight: 20 },
    { itemId: "SALMON", weight: 60 },
    { itemId: "PUFFERFISH", weight: 40 },
    { itemId: "GN_RAW_TROUT", weight: 30 },
    { itemId: "GN_RAW_BASS", weight: 15 },
    { itemId: "GN_RAW_CARP", weight: 12 },
    { itemId: "GN_SHRIMP", weight: 15 },
    { itemId: "WT_SHUIZHI", weight: 54 },
    { itemId: "WT_OUZHOULUYU", weight: 20 },
    { itemId: "WT_NIANYU", weight: 40 },
    { itemId: "WT_BINGYU", weight: 20 },
    { itemId: "WT_ZHANYU", weight: 50 },
    { itemId: "WT_JINYU", weight: 30 },
    { itemId: "WT_SHILAIMUYU", weight: 4 },
    { itemId: "WT_LONGXIA", weight: 25 },
    { itemId: "WT_LANLONGXIA", weight: 10 },
    { itemId: "WT_YNSHUIMU", weight: 8 },
    { itemId: "WT_YADAN", weight: 15 },
    { itemId: "WT_WUGUI", weight: 10 },
    { itemId: "WT_HEXIA", weight: 60 },
    { itemId: "WT_FEIQIYANGQIGUAN", weight: 20 },
    { itemId: "WT_SHIDIFUYU", weight: 3 },
    { itemId: "WT_JINGDIANYU", weight: 30 },
    { itemId: "WT_SHUIJINGYU", weight: 8 },
    { itemId: "WT_YOUNIYU", weight: 20 },
    { itemId: "WT_ZUANSHIHETUN", weight: 1 },
    { itemId: "WT_JINLI", weight: 5 },
    { itemId: "WT_SHUIPAOJINYU", weight: 20 },
    { itemId: "WT_EYU", weight: 4 },
    { itemId: "WT_HUOLIENIAO", weight: 1 },
    { itemId: "WT_HELI", weight: 10 }
];

const XIANSHUIYUER_DROPS = [

    { itemId: "SEAGRASS", weight: 5 },
    { itemId: "SEA_PICKLE", weight: 10 },
    { itemId: "KELP", weight: 10 },
    { itemId: "COD", weight: 50 },
    { itemId: "TROPICAL_FISH", weight: 30 },
    { itemId: "GN_RAW_TUNA", weight: 20 },
    { itemId: "GN_RAW_SQUID", weight: 15 },
    { itemId: "GN_CRAB", weight: 20 },
    { itemId: "WT_HUANGQIJINQIANGYU", weight: 42 },
    { itemId: "WT_JUSHI", weight: 30 },
    { itemId: "WT_HAIXING", weight: 40 },
    { itemId: "WT_RUANTIDONGWU", weight: 30 },
    { itemId: "WT_BEIKE", weight: 20 },
    { itemId: "WT_HAIOU", weight: 5 },
    { itemId: "WT_HAIDAN", weight: 40 },
    { itemId: "WT_TENGFHU", weight: 45 },
    { itemId: "WT_HAIKUI", weight: 38 },
    { itemId: "WT_JIJUXIE", weight: 26 },
    { itemId: "WT_HAIZHE", weight: 30 },
    { itemId: "WT_SHIDAN", weight: 20 },
    { itemId: "WT_HAILUO", weight: 35 },
    { itemId: "WT_CHENGZI", weight: 30 },
    { itemId: "WT_HUAJIAO", weight: 5 },
    { itemId: "WT_SHENGHAO", weight: 10 },
    { itemId: "WT_BAOYU", weight: 12 },
    { itemId: "WT_HAISHEN", weight: 15 },
    { itemId: "WT_TUXIA", weight: 20 },
    { itemId: "WT_SHACHONG", weight: 10 },
    { itemId: "WT_DAIYU", weight: 5 },
    { itemId: "WT_HAITU", weight: 15 }
];

const XIANSHUIYUER_2_DROPS = [
    { itemId: "NAUTILUS_SHELL", weight: 30 },
    { itemId: "HEART_OF_THE_SEA", weight: 10 },
    { itemId: "GN_GUARDIAN_FIN", weight: 15 },
    { itemId: "GN_RAW_MACKEREL", weight: 20 },
    { itemId: "GN_RAW_EEL", weight: 20 },
    { itemId: "GN_RAW_PIKE", weight: 20 },
    { itemId: "WT_SHAYU", weight: 1 },
    { itemId: "WT_NIANYUWANG", weight: 8 },
    { itemId: "WT_JINXUEYU", weight: 20 },
    { itemId: "WT_SHUIDIYU", weight: 35 },
    { itemId: "WT_JINGYU", weight: 1 },
    { itemId: "WT_ZHANGYU", weight: 5 },
    { itemId: "WT_YINGWULUO", weight: 30 },
    { itemId: "WT_LANJING", weight: 1 },
    { itemId: "WT_POJIUDEYUWANG", weight: 25 },
    { itemId: "WT_PIPAYU", weight: 15 },
    { itemId: "WT_SHSHUIMU", weight: 32 },
    { itemId: "WT_HAIMIANBAOBAO", weight: 2 },
    { itemId: "WT_NIUPIXUE", weight: 10 },
    { itemId: "WT_SHENHAISHILAIMU", weight: 12 },
    { itemId: "WT_HAIXIANG", weight: 5 },
    { itemId: "WT_HUOMAN", weight: 20 },
    { itemId: "WT_BQBFENSESHUIMU", weight: 25 },
    { itemId: "WT_DIWANGXIE", weight: 2 },
    { itemId: "WT_DONGYANGYU", weight: 15 },
    { itemId: "WT_PAOCAIGUO", weight: 25 }
];

const SHUIGUOYUER_DROPS = [
    { itemId: "WT_YINGTAOYU", weight: 50 },
    { itemId: "WT_BOLUOYU", weight: 45 },
    { itemId: "WT_LANMEIYU", weight: 45 },
    { itemId: "WT_PUTAOYU", weight: 45 },
    { itemId: "WT_HUANGGUAYU", weight: 45 },
    { itemId: "WT_HULUOBOYU", weight: 45 },
    { itemId: "WT_TIANCAIYU", weight: 45 },
    { itemId: "WT_XIAOMAIYU", weight: 55 },
    { itemId: "WT_XIGUAYU", weight: 55 },
    { itemId: "WT_TUDOUYU", weight: 55 },
    { itemId: "WT_YUNDUOYU", weight: 10 },
    { itemId: "WT_HAIZEIWANGYU", weight: 5 },
    { itemId: "WT_XIGUASHAYU", weight: 1 },
    { itemId: "WT_NANGUAZZ", weight: 35 }
];

const HETUNYUER_DROPS = [
    { itemId: "WT_PUFFERFISH_NORMAL", weight: 55 },
    { itemId: "WT_PUFFERFISH_MECHANICAL", weight: 20 },
    { itemId: "WT_PUFFERFISH_BEE", weight: 20 },
    { itemId: "WT_PUFFERFISH_SLIME", weight: 12 },
    { itemId: "WT_PUFFERFISH_HIM", weight: 8 },
    { itemId: "WT_PUFFERFISH_MR", weight: 20 },
    { itemId: "WT_PUFFERFISH_LAVA", weight: 8 },
    { itemId: "WT_PUFFERFISH_RADIATION", weight: 8 },
    { itemId: "WT_PUFFERFISH_EMBER", weight: 10 },
    { itemId: "WT_PUFFERFISH_BIOHAZARD", weight: 12 },
    { itemId: "WT_PUFFERFISH_GLOW", weight: 13 },
    { itemId: "WT_PUFFERFISH_NEEDLEFISH", weight: 14 },
    { itemId: "WT_PUFFERFISH_GRASS_BLOCK", weight: 16 },
    { itemId: "WT_PUFFERFISH_SACRIFICE", weight: 9 },
    { itemId: "WT_PUFFERFISH_WHITE", weight: 25 },
    { itemId: "WT_PUFFERFISH_PINK", weight: 25 },
    { itemId: "WT_PUFFERFISH_RED", weight: 25 },
    { itemId: "WT_PUFFERFISH_ORANGE", weight: 25 },
    { itemId: "WT_PUFFERFISH_YELLOW", weight: 25 },
    { itemId: "WT_PUFFERFISH_YELLOW_GREEN", weight: 25 },
    { itemId: "WT_PUFFERFISH_CYAN", weight: 25 },
    { itemId: "WT_PUFFERFISH_LIGHT_BLUE", weight: 25 },
    { itemId: "WT_PUFFERFISH_PURPLE", weight: 25 },
    { itemId: "WT_PUFFERFISH_MAGENTA", weight: 25 },
    { itemId: "WT_PUFFERFISH_BROWN", weight: 25 },
    { itemId: "WT_PUFFERFISH_CARROT", weight: 20 },
    { itemId: "WT_PUFFERFISH_AMETHYST", weight: 16 },
    { itemId: "WT_PUFFERFISH_EMERALD", weight: 4 },
    { itemId: "WT_ZUANSHIHETUN", weight: 5 },
    { itemId: "WT_PUFFERFISH_GOLD", weight: 6 }
];

WT_setupFishing({
  rodId: "WT_BAIWEIDIAOGAN",
  baits: {
    "WT_DANSHUIYUER": DANSHUIYUER_DROPS,
    "WT_XIANSHUIYUER": XIANSHUIYUER_DROPS,
    "WT_XIANSHUIYUER_2": XIANSHUIYUER_2_DROPS,
    "WT_SHUIGUOYUER": SHUIGUOYUER_DROPS,
    "WT_HETUNYUER": HETUNYUER_DROPS,
  }
});
